[versions]
androidGradlePlugin = "9.4.0"
healthServices = "1.1.0-rc02"
watchfaceComplications = "1.3.0"
junit = "4.13.2"
guava = "33.4.8-android"
androidTestRunner = "1.7.0"
androidTestJunit = "1.3.0"
androidCore = "1.19.1"

[libraries]
android-core = { module = "androidx.core:core", version.ref = "androidCore" }
health-services = { module = "androidx.health:health-services-client", version.ref = "healthServices" }
health-services-proto = { module = "androidx.health:health-services-client-proto", version.ref = "healthServices" }
watchface-complications = { module = "androidx.wear.watchface:watchface-complications-data-source", version.ref = "watchfaceComplications" }
junit = { module = "junit:junit", version.ref = "junit" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
android-test-runner = { module = "androidx.test:runner", version.ref = "androidTestRunner" }
android-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidTestJunit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
